<?php

namespace Proxies\__CG__\Admin\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \Admin\AdminBundle\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'nom', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'picture', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'brand', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'barCode', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'updateDate', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'file', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'idCategory');
        }

        return array('__isInitialized__', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'nom', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'picture', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'brand', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'barCode', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'updateDate', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'file', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Produit' . "\0" . 'idCategory');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture($picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', array($picture));

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', array());

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand($brand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', array($brand));

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', array());

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setBarCode($barCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBarCode', array($barCode));

        return parent::setBarCode($barCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getBarCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBarCode', array());

        return parent::getBarCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($updateDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', array($updateDate));

        return parent::setUpdateDate($updateDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', array());

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategory(\Admin\AdminBundle\Entity\Category $idCategory = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategory', array($idCategory));

        return parent::setIdCategory($idCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategory', array());

        return parent::getIdCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', array($file));

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', array());

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function lifecycleFileUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'lifecycleFileUpload', array());

        return parent::lifecycleFileUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function refreshUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'refreshUpdated', array());

        return parent::refreshUpdated();
    }

}
