
services:
    sonata.admin.Produit:
        class: Admin\AdminBundle\Admin\ProduitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Produit" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Produit
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
            
            
            
    sonata.admin.category:
        class: Admin\AdminBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "category" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
            
    sonata.admin.price:
        class: Admin\AdminBundle\Admin\PriceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "price" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Price
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
            
    sonata.admin.place:
        class: Admin\AdminBundle\Admin\PlaceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "place" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Place
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]