Front\FrontBundle\Entity\Place:
    type: entity
    table: place
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        latitude:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        longitude:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        address:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
